services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - DOMAIN_NAMES=${DOMAIN_NAMES}
    ports:
      - "443:443"
    volumes:
      - ./conf.d/:/etc/nginx/conf.d/
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nginx
networks:
  nginx:
    name: ${NETWORK_NAME}
    driver: bridge
    external: true